trigger:
- main

name: Deploy Bicep files

variables:
  azureServiceConnection: 'hotel-management-az-service-connection'
  resourceGroupName: 'hotel-management'
  location: 'eastus'
  templateFile: './main.bicep'
pool:
  name: self-hosted-linux

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'